# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://localhost:1313/"
title = "小组学习"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: params.author.name ↓ # 默认为下面配置的params.author.name ↓

[pagination]
  pagerSize = 5           # Number of articles displayed on the homepage  # 首页每页显示的文章数

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  weight = 1
  languageCode = "en"
  languageName = "EN"
[languages.zh-cn]
  weight = 2
  languageCode = "zh-CN"
  languageName = "简体中文"
  hasCJKLanguage = true
  [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "home"
        pre = ""
        post = ""
        name = "首页"
        pageref = "/"
        title = "Home"
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "archives"
        pre = ""
        post = ""
        name = "归档"
        pageref = "/posts/"
        title = "Posts"
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        pageref = "/tags/"
        title = "Tags"
    [languages.zh-cn.params]
      logoTitle = "小组学习"
      [languages.zh-cn.params.search]
        enable = true
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 50
        highlightTag = "em"
        absoluteURL = false
        [languages.zh-cn.params.search.algolia]
          index = "xxx"
          appID = ""
          searchKey = ""
        [languages.zh-cn.params.footer]
          enable = true
          # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
          custom = ''
          # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
          hugo = false
          # LoveIt 新增 | 0.2.0 是否显示版权信息
          copyright = true
          # LoveIt 新增 | 0.2.0 是否显示作者
          author = true
          # 网站创立年份
          since = 2023
          # ICP 备案信息，仅在中文显示
          icp = '' 
          # 许可协议信息 (支持 HTML 格式)
          license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>' 
      [languages.zh-cn.params.home]
        rss = 10
        [languages.zh-cn.params.home.posts]
            enable = true
            # 主页每页显示文章数量
            paginate = 8
        [languages.zh-cn.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.png"
          title = ""
          subtitle = ""
          typeit = true
          social = false
          disclaimer = ""
[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "This is Home"
  weight = 10
  identifier = "home"
  pageref = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"

[params]
  since = "2024"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = false     # if false, Rss feed instead of the summary

  author.name = "Hongsen"      # essential                     # 必需
  author.email = "me@example.com" # optional, for RSS             # 可选
  author.url = "/about"        # optional                      # 可选

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Fellowship"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # show language chooser in menu
  showMenuLanguageChooser = true
